import { useQuery } from '@tanstack/react-query'
import { Goal, ShieldCheck, Sparkles, Swords, Trophy, UserRound } from 'lucide-react'
import { useState } from 'react'
import { championshipApi } from '@/features/championships/championship.api'
import { statisticsApi } from '@/features/statistics/statistics.api'
import { assetUrl } from '@/shared/api/asset-url'

export function StatisticsPage() {
  const championships = useQuery({ queryKey: ['championships', 'options'], queryFn: () => championshipApi.list({ page: 1, pageSize: 50, sortBy: 'name', sortOrder: 'asc' }) })
  const [selected, setSelected] = useState(''); const championshipId = selected || championships.data?.data[0]?.id || ''
  const query = useQuery({ queryKey: ['statistics', championshipId], queryFn: () => statisticsApi.get(championshipId), enabled: Boolean(championshipId) }); const data = query.data
  return <><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold sm:text-3xl">Estatísticas</h1><p className="mt-2 text-sm text-slate-400">Os principais números da competição.</p></div><select aria-label="Selecionar campeonato" value={championshipId} onChange={(event) => setSelected(event.target.value)} className="h-10 max-w-56 rounded-xl border bg-white px-3 text-sm dark:bg-slate-900"><option value="">Selecione</option>{championships.data?.data.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.season}</option>)}</select></header>{query.isLoading ? <p className="mt-8 text-sm text-slate-400">Carregando...</p> : query.isError ? <p className="mt-8 text-sm text-red-500">Ocorreu um erro.</p> : data && <><section className="mt-7 grid grid-cols-2 gap-4 lg:grid-cols-4"><Metric icon={Goal} label="Gols" value={data.totalGoals} /><Metric icon={Sparkles} label="Média por jogo" value={data.averageGoals} /><Metric icon={Swords} label="Jogos realizados" value={data.finishedMatches} /><Metric icon={Trophy} label="Temporada" value={data.championship.season} /></section><section className="mt-5 grid gap-4 md:grid-cols-3"><Highlight icon={Swords} title="Melhor ataque" name={data.bestAttack?.team.name} detail={data.bestAttack ? `${data.bestAttack.goals} gols marcados` : undefined} image={data.bestAttack?.team.crestUrl} /><Highlight icon={ShieldCheck} title="Melhor defesa" name={data.bestDefense?.team.name} detail={data.bestDefense ? `${data.bestDefense.goals} gols sofridos` : undefined} image={data.bestDefense?.team.crestUrl} /><Highlight icon={UserRound} title="Artilheiro" name={data.topScorer?.player.name} detail={data.topScorer ? `${data.topScorer.goals} gols · ${data.topScorer.player.team.name}` : undefined} image={data.topScorer?.player.photoUrl} /></section></>}</>
}

function Metric({ icon: Icon, label, value }: { icon: typeof Goal; label: string; value: string | number }) { return <article className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-900"><Icon className="text-brand-600" size={21} /><p className="mt-5 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-400">{label}</p></article> }
function Highlight({ icon: Icon, title, name, detail, image }: { icon: typeof Goal; title: string; name?: string; detail?: string; image?: string | null }) { const source = assetUrl(image ?? null); return <article className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex items-center gap-2 text-sm font-semibold text-slate-500"><Icon size={18} />{title}</div><div className="mt-6 flex items-center gap-3">{source ? <img src={source} alt="" className="size-12 rounded-xl object-cover" /> : <span className="grid size-12 place-items-center rounded-xl bg-slate-100 dark:bg-slate-800"><Icon size={21} /></span>}<div><p className="font-bold">{name ?? 'Sem dados'}</p><p className="mt-1 text-xs text-slate-400">{detail ?? 'Aguardando resultados'}</p></div></div></article> }
