import { useQuery } from '@tanstack/react-query'
import { BarChart3, Shield } from 'lucide-react'
import { useMemo, useState } from 'react'
import { championshipApi } from '@/features/championships/championship.api'
import { standingApi } from '@/features/standings/standing.api'
import type { Standing } from '@/features/standings/standing.types'
import { assetUrl } from '@/shared/api/asset-url'

type SortKey = keyof Pick<Standing, 'position' | 'points' | 'played' | 'wins' | 'draws' | 'losses' | 'goalsFor' | 'goalsAgainst' | 'goalDifference'>

export function StandingsPage() {
  const championships = useQuery({ queryKey: ['championships', 'options'], queryFn: () => championshipApi.list({ page: 1, pageSize: 50, sortBy: 'name', sortOrder: 'asc' }) })
  const [selected, setSelected] = useState(''); const championshipId = selected || championships.data?.data[0]?.id || ''; const [sort, setSort] = useState<{ key: SortKey; direction: 'asc' | 'desc' }>({ key: 'position', direction: 'asc' })
  const query = useQuery({ queryKey: ['standings', championshipId], queryFn: () => standingApi.list(championshipId), enabled: Boolean(championshipId) })
  const rows = useMemo(() => [...(query.data?.standings ?? [])].sort((a, b) => (a[sort.key] - b[sort.key]) * (sort.direction === 'asc' ? 1 : -1)), [query.data, sort])
  const changeSort = (key: SortKey) => setSort((current) => ({ key, direction: current.key === key && current.direction === 'asc' ? 'desc' : 'asc' }))
  return <><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold sm:text-3xl">Classificação</h1><p className="mt-2 text-sm text-slate-400">Acompanhe a campanha de cada equipe.</p></div><select aria-label="Selecionar campeonato" value={championshipId} onChange={(event) => setSelected(event.target.value)} className="h-10 max-w-56 rounded-xl border bg-white px-3 text-sm dark:bg-slate-900"><option value="">Selecione</option>{championships.data?.data.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.season}</option>)}</select></header>{!championshipId ? <Empty /> : query.isLoading ? <p className="mt-8 text-sm text-slate-400">Carregando...</p> : query.isError ? <p className="mt-8 text-sm text-red-500">Ocorreu um erro.</p> : rows.length === 0 ? <Empty /> : <section className="mt-7 overflow-x-auto rounded-2xl border bg-white shadow-sm dark:bg-slate-900"><table className="w-full min-w-245 text-center text-sm"><thead><tr className="border-b text-xs text-slate-400"><Header label="#" field="position" sort={changeSort} /><th className="px-4 py-3 text-left font-medium">Time</th><Header label="PTS" field="points" sort={changeSort} /><Header label="J" field="played" sort={changeSort} /><Header label="V" field="wins" sort={changeSort} /><Header label="E" field="draws" sort={changeSort} /><Header label="D" field="losses" sort={changeSort} /><Header label="GP" field="goalsFor" sort={changeSort} /><Header label="GC" field="goalsAgainst" sort={changeSort} /><Header label="SG" field="goalDifference" sort={changeSort} /><th className="px-4 py-3 font-medium">%</th></tr></thead><tbody>{rows.map((row) => <StandingRow key={row.id} row={row} />)}</tbody></table></section>}</>
}

function Header({ label, field, sort }: { label: string; field: SortKey; sort: (key: SortKey) => void }) { return <th onClick={() => sort(field)} className="cursor-pointer px-4 py-3 font-medium">{label}</th> }
function StandingRow({ row }: { row: Standing }) { const crest = assetUrl(row.team.crestUrl); const efficiency = row.played ? ((row.points / (row.played * 3)) * 100).toFixed(1) : '0.0'; return <tr className="border-b last:border-0"><td className="px-4 py-4 font-bold">{row.position}</td><td className="px-4 py-4"><div className="flex min-w-48 items-center gap-3 text-left">{crest ? <img src={crest} alt="" className="size-9 rounded-lg object-cover" /> : <span className="grid size-9 place-items-center rounded-lg bg-slate-100 dark:bg-slate-800"><Shield size={16} /></span>}<span className="font-semibold">{row.team.name}</span></div></td><td className="px-4 py-4 font-bold text-brand-700 dark:text-brand-400">{row.points}</td><td>{row.played}</td><td>{row.wins}</td><td>{row.draws}</td><td>{row.losses}</td><td>{row.goalsFor}</td><td>{row.goalsAgainst}</td><td>{row.goalDifference}</td><td className="px-4">{efficiency}%</td></tr> }
function Empty() { return <div className="mt-7 grid min-h-72 place-items-center rounded-2xl border border-dashed bg-white text-center dark:bg-slate-900"><div><BarChart3 className="mx-auto text-slate-300 dark:text-slate-700" size={42} /><h2 className="mt-4 font-bold">Classificação indisponível</h2><p className="mt-2 text-sm text-slate-400">Gere a tabela de um campeonato para começar.</p></div></div> }
