import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronLeft, ChevronRight, MapPin, Pencil, Plus, Search, Shield, Trash2, Users } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { teamRoutes } from '@/app/route-paths'
import { teamApi } from '@/features/teams/team.api'
import type { Team } from '@/features/teams/team.types'
import { assetUrl } from '@/shared/api/asset-url'

export function TeamsPage() {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const queryClient = useQueryClient()
  const query = useQuery({ queryKey: ['teams', { search, page }], queryFn: () => teamApi.list({ search: search || undefined, page }) })
  const remove = useMutation({ mutationFn: teamApi.remove, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['teams'] }) })
  const teams = query.data?.data ?? []; const meta = query.data?.meta
  return <><header className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Times</h1><p className="mt-2 text-sm text-slate-400">Gerencie os times participantes.</p></div><Link to={teamRoutes.create} className="flex h-11 shrink-0 items-center gap-2 rounded-xl bg-brand-600 px-4 text-sm font-semibold text-white shadow-lg shadow-brand-600/20 hover:bg-brand-700"><Plus size={18} /><span className="hidden sm:inline">Adicionar time</span><span className="sm:hidden">Adicionar</span></Link></header><section className="mt-7"><div className="mb-4 flex items-center justify-between"><label className="relative block w-40"><span className="sr-only">Pesquisar times</span><Search className="absolute top-1/2 left-2.5 -translate-y-1/2 text-slate-400" size={14} /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} placeholder="Buscar" className="h-8 w-full rounded-lg border bg-white pr-3 pl-8 text-xs dark:bg-slate-900" /></label><p className="text-xs text-slate-400">{meta?.total ?? 0} time(s)</p></div>{query.isLoading ? null : query.isError ? <div className="grid min-h-64 place-items-center text-sm text-red-500">Ocorreu um erro.</div> : teams.length === 0 ? <EmptyTeams /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{teams.map((team) => <TeamCard key={team.id} team={team} remove={() => remove.mutate(team.id)} />)}</div>}{meta && meta.totalPages > 1 && <div className="mt-6 flex items-center justify-between"><p className="text-xs text-slate-400">Página {meta.page} de {meta.totalPages}</p><div className="flex gap-2"><button aria-label="Página anterior" disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="grid size-9 place-items-center rounded-lg border bg-white disabled:opacity-30 dark:bg-slate-900"><ChevronLeft size={16} /></button><button aria-label="Próxima página" disabled={page >= meta.totalPages} onClick={() => setPage((value) => value + 1)} className="grid size-9 place-items-center rounded-lg border bg-white disabled:opacity-30 dark:bg-slate-900"><ChevronRight size={16} /></button></div></div>}</section></>
}

function TeamCard({ team, remove }: { team: Team; remove: () => void }) {
  const crest = assetUrl(team.crestUrl)
  return <article className="group overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:bg-slate-900"><div className="h-1.5" style={{ background: `linear-gradient(90deg, ${team.primaryColor} 50%, ${team.secondaryColor} 50%)` }} /><div className="p-5"><div className="flex items-start gap-4">{crest ? <img src={crest} alt={`Escudo do ${team.name}`} className="size-15 rounded-2xl border object-cover" /> : <span className="grid size-15 shrink-0 place-items-center rounded-2xl bg-slate-100 text-slate-400 dark:bg-slate-800"><Shield size={27} /></span>}<div className="min-w-0 flex-1"><h2 className="truncate font-bold">{team.name}</h2><p className="mt-1 flex items-center gap-1.5 text-xs text-slate-400"><MapPin size={13} />{team.city} — {team.state}</p><p className="mt-2 text-xs text-slate-400">Técnico: {team.coach}</p></div></div><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="flex items-center gap-1.5 text-xs text-slate-400"><Users size={15} />{team._count.players} jogadores</span><div className="flex gap-1"><Link to={teamRoutes.edit(team.id)} aria-label={`Editar ${team.name}`} className="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800"><Pencil size={15} /></Link><button onClick={remove} aria-label={`Excluir ${team.name}`} className="grid size-8 cursor-pointer place-items-center rounded-lg text-slate-400 hover:bg-red-50 hover:text-red-600 dark:hover:bg-red-950/40"><Trash2 size={15} /></button></div></div></div></article>
}

function EmptyTeams() { return <div className="grid min-h-72 place-items-center rounded-2xl border border-dashed bg-white p-8 text-center dark:bg-slate-900"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-brand-50 text-brand-700 dark:bg-brand-950 dark:text-brand-300"><Shield size={27} /></span><h2 className="mt-4 font-bold">Nenhum time cadastrado</h2><p className="mt-2 text-sm text-slate-400">Adicione os times que participarão dos campeonatos.</p><Link to={teamRoutes.create} className="mt-5 inline-flex rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">Adicionar time</Link></div></div> }
