import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, MapPin, Pencil, Trophy, X } from 'lucide-react'
import { useState } from 'react'
import { championshipApi } from '@/features/championships/championship.api'
import { matchApi } from '@/features/matches/match.api'
import type { Match } from '@/features/matches/match.types'
import { assetUrl } from '@/shared/api/asset-url'

type DialogMode = 'schedule' | 'result'

export function MatchesPage() {
  const [championshipId, setChampionshipId] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [dialog, setDialog] = useState<{ match: Match; mode: DialogMode } | null>(null)
  const championships = useQuery({ queryKey: ['championships', 'options'], queryFn: () => championshipApi.list({ page: 1, pageSize: 50, sortBy: 'name', sortOrder: 'asc' }) })
  const query = useQuery({ queryKey: ['matches', { championshipId, status, page }], queryFn: () => matchApi.list({ championshipId: championshipId || undefined, status: status || undefined, page }) })
  const matches = query.data?.data ?? []; const meta = query.data?.meta
  return <><header><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Jogos</h1><p className="mt-2 text-sm text-slate-400">Consulte partidas, datas e resultados.</p></header><section className="mt-7"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><select aria-label="Filtrar por campeonato" value={championshipId} onChange={(event) => { setChampionshipId(event.target.value); setPage(1) }} className="h-9 max-w-52 rounded-lg border bg-white px-3 text-xs dark:bg-slate-900"><option value="">Todos os campeonatos</option>{championships.data?.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Filtrar por status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }} className="h-9 rounded-lg border bg-white px-3 text-xs dark:bg-slate-900"><option value="">Todos</option><option value="SCHEDULED">Agendados</option><option value="FINISHED">Finalizados</option><option value="POSTPONED">Adiados</option></select></div><p className="text-xs text-slate-400">{meta?.total ?? 0} jogo(s)</p></div>{query.isLoading ? null : query.isError ? <div className="grid min-h-64 place-items-center text-sm text-red-500">Ocorreu um erro.</div> : matches.length === 0 ? <EmptyMatches /> : <div className="space-y-3">{matches.map((match) => <MatchCard key={match.id} match={match} edit={() => setDialog({ match, mode: 'schedule' })} result={() => setDialog({ match, mode: 'result' })} />)}</div>}{meta && meta.totalPages > 1 && <div className="mt-5 flex items-center justify-between"><p className="text-xs text-slate-400">Página {meta.page} de {meta.totalPages}</p><div className="flex gap-2"><button aria-label="Página anterior" disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="grid size-9 place-items-center rounded-lg border bg-white disabled:opacity-30 dark:bg-slate-900"><ChevronLeft size={16} /></button><button aria-label="Próxima página" disabled={page >= meta.totalPages} onClick={() => setPage((value) => value + 1)} className="grid size-9 place-items-center rounded-lg border bg-white disabled:opacity-30 dark:bg-slate-900"><ChevronRight size={16} /></button></div></div>}</section>{dialog && <MatchDialog key={`${dialog.match.id}-${dialog.mode}`} match={dialog.match} mode={dialog.mode} close={() => setDialog(null)} />}</>
}

function MatchCard({ match, edit, result }: { match: Match; edit: () => void; result: () => void }) {
  const date = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(match.scheduledAt)); const finished = match.status === 'FINISHED'
  return <article className="rounded-2xl border bg-white p-4 shadow-sm sm:p-5 dark:bg-slate-900"><div className="flex items-center justify-between gap-3 border-b pb-3"><div><p className="text-xs font-semibold text-brand-700 dark:text-brand-400">{match.championship.name}</p><p className="mt-1 text-xs text-slate-400">Rodada {match.round}{match.groupName ? ` · Grupo ${match.groupName}` : ''}</p></div><div className="flex gap-1"><button onClick={edit} aria-label="Editar data e local" className="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><Pencil size={15} /></button><button onClick={result} className="rounded-lg bg-brand-50 px-3 py-2 text-xs font-semibold text-brand-700 dark:bg-brand-950 dark:text-brand-300">{finished ? 'Editar placar' : 'Resultado'}</button></div></div><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 py-5"><Team team={match.homeTeam} align="right" /><div className="min-w-20 text-center">{finished ? <span className="text-2xl font-bold">{match.homeScore} <span className="text-slate-300">×</span> {match.awayScore}</span> : <span className="text-sm font-semibold text-slate-400">×</span>}</div><Team team={match.awayTeam} align="left" /></div><div className="flex flex-wrap justify-center gap-x-5 gap-y-1 border-t pt-3 text-xs text-slate-400"><span className="flex items-center gap-1.5"><Clock3 size={13} />{date}</span><span className="flex items-center gap-1.5"><MapPin size={13} />{match.venue}</span></div></article>
}

function Team({ team, align }: { team: Match['homeTeam']; align: 'left' | 'right' }) { const crest = assetUrl(team.crestUrl); return <div className={`flex items-center gap-2 ${align === 'right' ? 'flex-row-reverse text-right' : ''}`}>{crest ? <img src={crest} alt="" className="size-10 rounded-xl object-cover" /> : <span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 dark:bg-slate-800"><Trophy size={17} /></span>}<span className="line-clamp-2 text-sm font-semibold">{team.name}</span></div> }

function MatchDialog({ match, mode, close }: { match: Match; mode: DialogMode; close: () => void }) {
  const queryClient = useQueryClient(); const localDate = new Date(new Date(match.scheduledAt).getTime() - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 16); const [scheduledAt, setScheduledAt] = useState(localDate); const [venue, setVenue] = useState(match.venue); const [homeScore, setHomeScore] = useState(match.homeScore ?? 0); const [awayScore, setAwayScore] = useState(match.awayScore ?? 0)
  const mutation = useMutation({ mutationFn: () => mode === 'schedule' ? matchApi.update(match.id, { scheduledAt: new Date(scheduledAt).toISOString(), venue }) : matchApi.result(match.id, { homeScore, awayScore }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['matches'] }); close() } })
  return <div role="dialog" aria-modal="true" aria-labelledby="match-dialog-title" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-900"><header className="flex items-center justify-between"><h2 id="match-dialog-title" className="font-bold">{mode === 'schedule' ? 'Editar partida' : 'Registrar resultado'}</h2><button onClick={close} aria-label="Fechar" className="grid size-8 place-items-center rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"><X size={18} /></button></header>{mode === 'schedule' ? <div className="mt-6 space-y-4"><label className="block text-sm font-semibold">Data e horário<input type="datetime-local" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} className="mt-2 h-11 w-full rounded-xl border bg-transparent px-3 text-sm" /></label><label className="block text-sm font-semibold">Local<input value={venue} onChange={(event) => setVenue(event.target.value)} className="mt-2 h-11 w-full rounded-xl border bg-transparent px-3 text-sm" /></label></div> : <div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-end gap-4 text-center"><label className="text-sm font-semibold">{match.homeTeam.name}<input type="number" min={0} max={99} value={homeScore} onChange={(event) => setHomeScore(Number(event.target.value))} className="mt-3 h-14 w-full rounded-xl border bg-transparent text-center text-xl font-bold" /></label><span className="pb-4 text-slate-400">×</span><label className="text-sm font-semibold">{match.awayTeam.name}<input type="number" min={0} max={99} value={awayScore} onChange={(event) => setAwayScore(Number(event.target.value))} className="mt-3 h-14 w-full rounded-xl border bg-transparent text-center text-xl font-bold" /></label></div>}{mutation.isError && <p className="mt-4 text-sm text-red-500">Ocorreu um erro.</p>}<button onClick={() => mutation.mutate()} disabled={mutation.isPending} className="mt-6 h-11 w-full rounded-xl bg-brand-600 text-sm font-semibold text-white disabled:opacity-60">Salvar</button></div></div>
}

function EmptyMatches() { return <div className="grid min-h-72 place-items-center rounded-2xl border border-dashed bg-white p-8 text-center dark:bg-slate-900"><div><CalendarDays className="mx-auto text-slate-300 dark:text-slate-700" size={42} /><h2 className="mt-4 font-bold">Nenhum jogo encontrado</h2><p className="mt-2 max-w-sm text-sm text-slate-400">Adicione participantes e gere a tabela pelo menu do campeonato.</p></div></div> }
